# Generated by Django 5.0.6 on 2025-03-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_delete_youtubevideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='published_date',
            new_name='published_at',
        ),
        migrations.RemoveField(
            model_name='video',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='video',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
