# Generated by Django 5.0.6 on 2025-03-08 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone  # Import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_rename_published_date_video_published_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='published_at',
        ),
        migrations.AddField(
            model_name='video',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(default='default_thumbnail.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='upload_date',
            field=models.DateTimeField(default=timezone.datetime(2025, 9, 3)),  # Fixed
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default='https://youtube.com'),
        ),
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.BooleanField(default=False)),
                ('liked', models.BooleanField(default=False)),
                ('commented', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
        ),
    ]