# Generated by Django 5.0.6 on 2025-03-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_remove_video_description_remove_video_published_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='upload_date',
            field=models.DateTimeField(default='now'),
        ),
    ]
