# Generated by Django 5.0.6 on 2025-03-09 00:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_alter_video_upload_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='videos.video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='comments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(default='https://example.com/default_thumbnail.jpg'),
        ),
        migrations.AlterField(
            model_name='video',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
