# Generated by Django 5.0.6 on 2025-03-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_video_channel_video_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.AddField(
            model_name='video',
            name='embedded_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
