# Generated by Django 5.0.6 on 2025-03-13 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_alter_comment_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='comment_count',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
