# Generated by Django 5.0.6 on 2025-03-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='comments',
            new_name='comments_count',
        ),
        migrations.AddField(
            model_name='video',
            name='positive_comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
