# Generated by Django 5.0.6 on 2025-03-15 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0016_rename_comments_video_comments_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_avatar',
            field=models.URLField(default='https://via.placeholder.com/40'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='videos.video'),
        ),
    ]
