# Generated by Django 5.0.6 on 2025-03-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0017_comment_user_avatar_alter_comment_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
