# Generated by Django 5.0.6 on 2025-05-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0020_videosimilarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
